site_name: MoneyMinds
repo_url: https://github.com/eduwxyz/MoneyMinds/
repo_name: MoneyMinds
edit_uri: https://github.com/eduwxyz/MoneyMinds/tree/master/docs/

theme:
  name: material
  palette:
    primary: deep_orange
    accent: amber
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extras.css


plugins: 
- mkdocstrings:
    handlers:
      python:
        paths: [money_minds]
